name: caro_game
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  permission_handler: ^10.2.0
  nearby_connections: ^3.2.0
  lottie: ^2.2.0
  extended_image: ^7.0.0
  assets_audio_player: ^3.0.6
  device_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/audios/
